### ISSUE TITLE
Ranks seem to be messed up

### ISSUE THREAD

**Issue by Wylith** [artfcl-intlgnce/XXMC#38] opened 2016-10-08 18:56 UTC
![screenshot 356](https://cloud.githubusercontent.com/assets/22691538/19215273/33048f3e-8d67-11e6-8aa3-fe00c134a093.png)
 Currently Heisenberg rank, next rank-up is supposed to be Empire, says Chemist when I do /rankup

And name does not change

**Comment by artfcl-intlgnce** [comment] 2016-10-08 19:53
I don't expect anyone to get to Prestige for several months, so this is being prioritized lower than some of the Showstopper defects. Setting for release 1.3 (october 30)

**Comment by mat290** [comment] 2016-10-14 23:49
If you want to task this as one of my to-dos.

**Comment by artfcl-intlgnce** [comment] 2016-11-05 06:56
@mat290 somehow a player is already at Heisenberg so this has come towards top of pile. Ask me on Discord for the EZRanks plugin config when u get a chance

**Comment by artfcl-intlgnce** [comment] 2016-12-07 07:50
TNTReflexx got there okay, so closing this as we are unable to reproduce

**Closed as completed by artfcl-intlgnce** 2016-12-07 07:50 UTC
Labels: bug, In Progress, Priority 1, Engineering Team, Factions
